<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Supplus.Comunicacao\Supplus.Comunicacao.csproj" />
    <ProjectReference Include="..\..\Shared\Supplus.Exceptions\Supplus.Exceptions.csproj" />
    <ProjectReference Include="..\Supplus.Application\Supplus.Application.csproj" />
    <ProjectReference Include="..\Supplus.Infrastructure\Supplus.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>
