<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f832b7f9-f2ab-4e41-b198-117e4ea4dcfb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Supplus.Comunicacao\Supplus.Comunicacao.csproj" />
    <ProjectReference Include="..\..\Shared\Supplus.Exceptions\Supplus.Exceptions.csproj" />
    <ProjectReference Include="..\Supplus.Application\Supplus.Application.csproj" />
    <ProjectReference Include="..\Supplus.Infrastructure\Supplus.Infrastructure.csproj" />
  </ItemGroup>

</Project>
