name: PR Validation

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codigo
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar solucao
        run: dotnet build --no-restore --configuration Release

      - name: Executar testes     
        env:
          ConnectionStrings__PostgreSql: ${{ secrets.POSTGRESQL_CONNECTION_STRING }}
          Config__Jwt__ChaveAssinatura: ${{ secrets.JWT_CHAVE_ASSINATURA}}
          Config__Jwt__ExpiracaoEmMinutos: ${{ secrets.JWT_EXPIRACAO_EM_MINUTOS }}
          Test: true
        run: dotnet test --no-build --configuration Release --verbosity normal
